# Keep GitHub Actions scheduled workflows alive.
name: keep_alive

on:
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          secret: ${{ secrets.KEEP_ALIVE_TOKEN }}
          repos: 
             - ${{ github.owner }}/test-keep-alive
             - ${{ github.owner }}/test-keep-alive-1
